#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
This tool queries information from Rapid7 InsightVM via API.
'''

from __future__ import (absolute_import, division, print_function)

import os
import sys
import argparse
import yaml
import json
import time
from py_insightvm_sdk.app_client import AppClient

__author__ = "Paul Greenberg @greenpau"
__version__ = "1.0"
__maintainer__ = "Paul Greenberg"
__email__ = "greenpau@outlook.com"
__status__ = "Alpha"

def main():
    '''
    Main function.
    '''
    descr = str(os.path.basename(__file__)) + ' - Rapid7 InsightVM API Client \n\n'
    epil = '\ndocumentation: https://github.com/greenpau/py_insightvm_sdk\n\n'
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                     add_help=True, description=descr, epilog=epil)

    main_group = parser.add_argument_group(None)
    main_group.add_argument('-o', metavar='output', dest='output', type=argparse.FileType('w'),
                            default=sys.stdout, help='Write to output file (or stdout)')

    action_arg_group = parser.add_argument_group('Actions')
    action_group = action_arg_group.add_mutually_exclusive_group(required=True)
    action_group.add_argument('--get-asset', dest='get_asset', action='store_true', help='get data about a specific asset')
    action_group.add_argument('--get-assets', dest='get_assets', action='store_true', help='get assets')
    action_group.add_argument('--get-sites', dest='get_sites', action='store_true', help='get sites')
    action_group.add_argument('--get-tags', dest='get_tags', action='store_true', help='get tags')
    action_group.add_argument('--get-vulnerabilities', dest='get_vulnerabilities', action='store_true', help='get vulnerabilities')
    action_group.add_argument('--get-asset-groups', dest='get_asset_groups', action='store_true', help='get asset groups')
    action_group.add_argument('--get-asset-by-id', dest='get_asset_by_id', metavar='ID', type=int,
                              help='get data about a specific asset by its id')
    action_group.add_argument('--get-high-risk-asset-ids', dest='get_high_risk_asset_ids', action='store_true',
                              help='get the IDs of high risk assets')
    action_group.add_argument('--asset-file',  metavar='FILENAME', dest='asset_file', type=argparse.FileType('r'),
                              default=None, help='read data about a specific asset from a file')

    filter_arg_group = parser.add_argument_group('References and Filtering')
    filter_arg_group.add_argument('--asset-ref', metavar='FILENAME', dest='asset_ref', type=argparse.FileType('r'),
                                  default=None,
                                  help='The path to the file with asset references, i.e. output of --get-assets')
    filter_arg_group.add_argument('--vuln-ref-dir',  metavar='DIR', dest='vuln_ref_dir',
                                  default=None,
                                  help='The path to the directory with vulnerabilities')
    filter_arg_group.add_argument('--asset-data-category', dest='asset_data_category',
                                  choices=['vulnerabilities','services','software'], default=None,
                                  help='Asset data category')
    filter_arg_group.add_argument('--filter', dest='obj_filters', metavar='KEY:VALUE',
                                  action='append', help='Object filters, e.g. ip:1.1.1.1, name:nysrv1')
    filter_arg_group.add_argument('--with-vulnerabilities', dest='with_vulnerabilities',
                                  action='store_true', help='add vulnerabilities to the output')
    filter_arg_group.add_argument('--page-size', dest='page_size', metavar='NUMBER', type=int,
                                  default=None, help='limit on the page size per request in a query')
    filter_arg_group.add_argument('--page-limit', dest='page_limit', metavar='NUMBER', type=int,
                                  default=None, help='limit on the number of pages per query')
    filter_arg_group.add_argument('--limit', dest='limit', metavar='NUMBER', type=int,
                                  default=None, help='limit the number of output items')

    main_group.add_argument('--format', dest='output_fmt', choices=['json', 'csv', 'yaml'],
                            default="json", help='Output format')

    main_group.add_argument('--debug', dest='enable_debug', action='store_true',
                              help='Enable debugging')
    args = parser.parse_args()

    opts = {}
    if args.page_size:
        opts['page_size'] = args.page_size
    if args.page_limit:
        opts['page_limit'] = args.page_limit
    if args.limit:
        opts['limit'] = args.limit
    if args.with_vulnerabilities:
        opts['with_vulnerabilities'] = args.with_vulnerabilities

    cli = AppClient()
    if args.enable_debug:
        cli.debug()
    cli.output_fmt = args.output_fmt
    cli.set_vuln_ref_dir(args.vuln_ref_dir)
    data = None
    if args.get_asset_groups:
        data = cli.get_asset_groups()
    elif args.get_tags:
        data = cli.get_tags()
    elif args.get_sites:
        data = cli.get_sites()
    elif args.get_vulnerabilities:
        data = cli.get_vulnerabilities(opts)
    elif args.get_assets:
        data = cli.get_assets(opts)
    elif args.get_high_risk_asset_ids:
        if not args.asset_ref:
            raise Exception('parser', 'the --get-asset requires --asset-ref')
        data = cli.get_high_risk_asset_ids(args.asset_ref, opts)
    elif args.get_asset:
        if not args.asset_ref:
            raise Exception('parser', 'the --get-asset requires --asset-ref')
        if not args.obj_filters:
            raise Exception('parser', 'the --get-asset requires --filter')
        data = cli.get_assets_from_file(args.asset_ref, args.obj_filters)
    elif args.get_asset_by_id:
        data = cli.get_asset_by_id(args.get_asset_by_id, opts)
    elif args.asset_file:
        if not args.asset_data_category:
            raise Exception('parser', 'unsupported argument')
        data = cli.get_asset_data_from_file(args.asset_file, args.asset_data_category)
        args.output_fmt = "csv"
    else:
        raise Exception('parser', 'unsupported argument')

    if args.output_fmt == 'yaml':
        yaml.dump(data, args.output, default_flow_style=False)
    elif args.output_fmt == 'csv':
        args.output.write(data)
    else:
        json.dump(data, args.output, sort_keys=True, indent=4, separators=(',', ': '))

    return

if __name__ == '__main__':
    main()
